### ISSUE TITLE
Integrate Bitget wallet with BOB Gateway

### ISSUE THREAD

**Issue by gregdhill** [bob-collective/ui#64]
https://web3.bitget.com/en/docs/provider-api/btc.html#signPsbt

**Comment by tomjeatt** [comment]
Currently an issue with Wallet Connect:
https://github.com/WalletConnect/web3modal/issues/2383

Following up—may need something on Bitget's side.

**Comment by tomjeatt** [comment]
Tested and working, successfully bridging BTC to WBTC using Bitget. We will want to do some testing on EVM transfers etc., but that's outside the scope of this task.
